// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://midrzhzjvukzxcalyuzi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1pZHJ6aHpqdnVrenhjYWx5dXppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMzQxODgsImV4cCI6MjA3MjYxMDE4OH0.9v6MdUBhPA8a9cXSYXsDljDUmvGSCDtOzPZo25sJnp8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});